# Generated by Django 5.1.4 on 2025-01-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_delete_usuario_remove_lista_n_canciones_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['artista', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='artista',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='cancion',
            options={'ordering': ['album', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='lista',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='reproduccion',
            options={'ordering': ['cancion']},
        ),
    ]
